# -*- coding: utf-8 -*-
"""hphi.ipynb

Automatically generated by Colaboratory.
"""

# Commented out IPython magic to ensure Python compatibility.
!wget https://github.com/issp-center-dev/HPhi/releases/download/v3.3.1/HPhi-3.3.1.tar.gz
!tar xzvf HPhi-3.3.1.tar.gz
!mkdir -p HPhi-3.3.1.build
# %cd HPhi-3.3.1.build
!cmake ../HPhi-3.3.1/
!make
!make test
