# -*- coding: utf-8 -*-
"""tenes.ipynb

Automatically generated by Colaboratory.
"""

# Commented out IPython magic to ensure Python compatibility.
!apt-get install libscalapack-mpi-dev
!wget https://github.com/issp-center-dev/TeNeS/releases/download/v1.0.0/TeNeS-v1.0.0.tar.gz
!tar xzvf TeNeS-v1.0.0.tar.gz
!mkdir -p TeNeS-v1.0.0.build
# %cd TeNeS-v1.0.0.build
!cmake ../TeNeS-v1.0.0
!make
