# -*- coding: utf-8 -*-
"""quspin_miniconda.ipynb

Automatically generated by Colaboratory.


https://github.com/weinbe58/QuSpin

https://stackoverflow.com/questions/59330876/install-conda-package-to-google-colab

https://stackoverflow.com/questions/53031430/conda-environment-in-google-colab-google-colaboratory

https://github.com/weinbe58/QuSpin/issues/319
"""

!wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

# !sha256sum Miniconda3-latest-Linux-x86_64.sh
# 957d2f0f0701c3d1335e3b39f235d197837ad69a944fa6f5d8ad2c686b69df3b

#!bash Miniconda3-latest-Linux-x86_64.sh
#!bash Miniconda3-latest-Linux-x86_64.sh -b -f -p $HOME/miniconda3
!bash Miniconda3-latest-Linux-x86_64.sh -b -f -p /usr/local/

import sys
sys.path.append('/usr/local/lib/python3.7/site-packages')
#!ls /usr/local/lib/python3.7/site-packages

!conda update conda -y
!conda update --all -y

!conda install -q -y --prefix /usr/local -c weinbe58 quspin
!conda install -q -y --prefix /usr/local matplotlib
#!conda install -q -y --prefix /usr/local numpy scipy joblib six dill gmpy2 numba matplotlib

# downgrade numba to fix bug
# https://github.com/weinbe58/QuSpin/issues/319
!conda install -q -y --prefix /usr/local numba=0.48.0

!wget https://raw.githubusercontent.com/weinbe58/QuSpin/master/examples/scripts/example0.py

!python example0.py
