# -*- coding: utf-8 -*-
"""dsqss_2.0.3_clean.ipynb

Automatically generated by Colaboratory.
"""

# Commented out IPython magic to ensure Python compatibility.
!wget https://github.com/issp-center-dev/dsqss/releases/download/v2.0.3/dsqss-v2.0.3.tar.gz
!tar xvzf dsqss-v2.0.3.tar.gz
#!find ./dsqss-v2.0.3 -name '._*'
!find ./dsqss-v2.0.3 -name '._*' | xargs rm
!mkdir dsqss-v2.0.3.build
# %cd dsqss-v2.0.3.build
!cmake -DCMAKE_INSTALL_PREFIX=../usr ../dsqss-v2.0.3
!make
!ctest
!make install
#!source ../usr/share/dsqss/dsqssvars-2.0.3.sh
#!cat ../usr/share/dsqss/dsqssvars-2.0.3.sh
## https://stackoverflow.com/questions/56207920/how-to-add-the-path-to-pythonpath-in-google-colab
!echo $PATH
!echo $PYTHONPATH
import os
os.environ['PATH'] += ":/content/usr/bin"
os.environ['PYTHONPATH'] += ":/content/usr/lib/python3.6/site-packages"
!echo $PATH
!echo $PYTHONPATH
