# -*- coding: utf-8 -*-
"""quspin_miniconda.ipynb

Automatically generated by Colaboratory.


20201205

Python version of google colaboratory is 3.8

QuSpin works for python version <= 3.7

Need to activate older python each time to use QuSpin

https://datascience.stackexchange.com/questions/75948/how-to-setup-and-run-conda-on-google-colab/75979#75979

https://stackoverflow.com/questions/62610289/conda-activate-and-conda-init-fail-to-work-in-colab-as-per-june-2020

https://github.com/weinbe58/QuSpin

https://stackoverflow.com/questions/59330876/install-conda-package-to-google-colab

https://stackoverflow.com/questions/53031430/conda-environment-in-google-colab-google-colaboratory

https://github.com/weinbe58/QuSpin/issues/319

https://github.com/weinbe58/QuSpin/issues/359

https://github.com/conda/conda-build/issues/3938
"""

# try to get the bare minimum to get a new conda env working
conda_path = ''
try:
    conda_path = !which conda
finally:
    print('')

if (len(conda_path) == 0):
    print('installing miniconda')
    !wget https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh && bash Miniconda3-4.5.4-Linux-x86_64.sh -bfp /usr/local
    !conda update conda -y -q
    !source /usr/local/etc/profile.d/conda.sh
    !conda init 
    !conda install -n root _license -y -q
else:
    print('found miniconda')

conda_envs = !conda env list
res = [i for i in conda_envs if 'test36' in i]
if (len(res) == 0):
    print('not found test36 env', len(res))
    !conda create -y -q --name test36 python=3.6
else:
    print('found test36 env', len(res))

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# source activate test36
# 
# python
# import sys
# # maybe only need this the first time we run this notebook
# sys.path.append('/usr/local/lib/python3.6/site-packages')
# 
# print("Python version")
# print(sys.version)
#

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# source activate test36
# 
# conda install -q -y -c weinbe58 quspin
# conda install -q -y matplotlib
# ## downgrade numba to fix bug
# ## https://github.com/weinbe58/QuSpin/issues/319
# conda install -q -y numba=0.48.0
# 
# #wget https://raw.githubusercontent.com/weinbe58/QuSpin/master/examples/scripts/example0.py
# #python example0.py
# 
# wget https://raw.githubusercontent.com/ryuikaneko/quspin_example/master/square__heisenberg__static/square_heisenberg.py
# python square_heisenberg.py > dat

!cat dat
