# -*- coding: utf-8 -*-
"""install_RPMPS-T.ipynb

Automatically generated by Colaboratory.
"""

### download files
!git clone https://github.com/ITensor/ITensor
!git clone https://github.com/nlohmann/json
!git clone https://github.com/ToruNiina/toml11
!git clone https://github.com/ShimpeiGoto/RPMPS-T

# Commented out IPython magic to ensure Python compatibility.
### compile ITensor
# %cd ITensor/
## ITensor v3.1.6
!git checkout d4d05d9b8a2b6fed6bba8e2c3bf1633d5d0ab6ce
!sed \
 -e 's/PLATFORM=macos/#PLATFORM=macos/' \
 -e 's/BLAS_LAPACK_LIBFLAGS=-framework Accelerate/#BLAS_LAPACK_LIBFLAGS=-framework Accelerate/' \
 -e 's/#PLATFORM=lapack/PLATFORM=lapack/' \
 -e 's|#BLAS_LAPACK_LIBFLAGS=-lpthread -L/usr/lib -lblas -llapack|BLAS_LAPACK_LIBFLAGS=-lpthread -L/usr/lib -lblas -llapack|' \
 -e 's/DEBUGFLAGS=-DDEBUG -g -Wall -Wno-unknown-pragmas -pedantic/#DEBUGFLAGS=-DDEBUG -g -Wall -Wno-unknown-pragmas -pedantic/' \
 options.mk.sample > options.mk
!make

# Commented out IPython magic to ensure Python compatibility.
### compile RPMPS-T
!mkdir sample_RPMPS-T
# %cd sample_RPMPS-T
!cp ../../RPMPS-T/*.cc .
!cp ../../RPMPS-T/*.h .
!cp ../../RPMPS-T/*.py .
!cp ../../RPMPS-T/*.sample .
!sed 's|LIBRARY_DIR=.*|LIBRARY_DIR=../|g' Makefile.sample > Makefile
!cp setting.toml.sample setting.toml
!cp ../../json/single_include/nlohmann/json.hpp .
!cp ../../toml11/toml.hpp .
!cp -r ../../toml11/toml/ .
!make

# Commented out IPython magic to ensure Python compatibility.
### run RPMPS-T
!sed -i 's/^Sample.*/Sample = 32/g' setting.toml
!./RandomMPS
!cat sample_*.json
# %run PlotJackknife.py
