# -*- coding: utf-8 -*-
"""mvmc.ipynb

Automatically generated by Colaboratory.
"""

# Commented out IPython magic to ensure Python compatibility.
!wget https://github.com/issp-center-dev/mVMC/releases/download/v1.1.1/mVMC-1.1.1.tar.gz
!tar xzvf mVMC-1.1.1.tar.gz
!mv mVMC mVMC-1.1.1
!mkdir -p mVMC-1.1.1.build
# %cd mVMC-1.1.1.build/
### fix bug in mVMC-1.1.1
!sed -i 's/shared(eleCfg, eleProjCnt, eleIdx, eleNum, ip)/shared(eleCfg, eleProjCnt, eleIdx, eleNum)/g' ../mVMC-1.1.1/src/mVMC/include/../calham.c
!sed -i 's/shared(eleCfg, eleProjCnt, eleIdx, eleNum, ip)/shared(eleCfg, eleProjCnt, eleIdx, eleNum)/g' ../mVMC-1.1.1/src/mVMC/include/../calham_real.c
### end of fix bug in mVMC-1.1.1
!cmake ../mVMC-1.1.1/
!make
