# -*- coding: utf-8 -*-
"""materiapps_exclude_ermod.ipynb

Automatically generated by Colaboratory.
"""

!wget https://sf.net/projects/materiappslive/files/Debian/sources/setup.sh
!sh setup.sh
!apt-get install akaikkr task-alps bsa dsqss feram fermisurfer gamess-setup hphi lammps mvmc openmx paraview quantum-espresso respack vesta vmd-setup xcrysden

## install error?
#!apt-get install ermod
